# Generated by Django 3.0 on 2020-08-15 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('Hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('Hospital_name', models.CharField(max_length=50, unique=True)),
                ('Bed_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('Doctor_name', models.CharField(max_length=30)),
                ('Joining_date', models.DateField()),
                ('Speciality', models.CharField(max_length=30)),
                ('Salary', models.FloatField()),
                ('Experiance', models.IntegerField()),
                ('Hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h1.Hospital')),
            ],
        ),
    ]
