# Generated by Django 3.0 on 2020-08-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Hospital_id',
            new_name='Hospital',
        ),
    ]
